### ISSUE TITLE
Differentiate between mouse down and mouse up events to enable drag select of text with the mouse

### ISSUE THREAD

**Issue by peteward** [pdfme/pdfme#219]
### Is your feature request related to a problem? Please describe.

When you drag select text in a textbox using the mouse and release the mouse button outside of the text box you lose focus of the text box:

https://github.com/pdfme/pdfme/assets/7068515/e2d218fb-efc8-48b3-aaa4-b86ba683ad16

### Describe the solution you'd like

Differentiate between mouse down and mouse up events when taking action on select/deselect within the Designer main area, so that a mouse up will not deselect the text box.

### Describe alternatives you've considered

Leave unchanged

**Comment by hand-dot** [comment]
I think this issue is fixed.
can we close this?

![CleanShot 2023-11-04 at 14 33 32](https://github.com/pdfme/pdfme/assets/24843808/e9276f3c-5a92-4bfd-9915-37c2183d131d)

**Comment by peteward** [comment]
The issue is that the schema is deselected if you mouseup outside of the schema (if you accidentally drag-select from inside to outside of the schema). 

It's a minor issue, but it still exists.
