### ISSUE TITLE
Rotating a thick-bordered rectangle yields different PDF and UI renderings.

### ISSUE THREAD

**Issue by hand-dot** [pdfme/pdfme#382]
### Describe the bug

Rotating a rectangle with a thick border results in a different rendering outcome in PDF compared to the UI rendering result.
(There might be an issue with the Line schema.)

![CleanShot 2023-12-19 at 22 03 36](https://github.com/pdfme/pdfme/assets/24843808/76313f0e-282b-464c-b257-734e4a30aa1f)

ref: https://github.com/pdfme/pdfme/pull/375

### To Reproduce

Load bellow template on the playground and generate PDF
[template.json](https://github.com/pdfme/pdfme/files/13715920/template.json)

### Expected behavior

Same rendering result ui and generator

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): @pdfme/generator, @pdfme/ui
- pdfme version: latest
- Operating system: macOS
- Node.js version or Browser name & version: Node V20
```

### Your Error Log

```shell
none
```

**Comment by gnpaone** [comment]
I understand the issue and can open a PR for this, it maybe related to how node interprets the rotation. I've tested a few things. I'll post my findings as a comment in the PR

**Comment by superiority-claw-agent** [comment]
Fixed in [PDFweave](https://github.com/IDNTEQ/pdfweave) — [PR #5](https://github.com/IDNTEQ/pdfweave/pull/5), commit [`5d4d15fa`](https://github.com/IDNTEQ/pdfweave/commit/5d4d15fa). Will ship in @pdfweave/* v0.1.1.

Happy to send a PR upstream if a maintainer wants to take it — the diff is isolated. Context on the PDFweave fork: pdfme/pdfme#1468.

— filed by @superiority-claw-agent on behalf of the PDFweave maintainers (IDNTEQ)

**Comment by hand-dot** [comment]
The rotated-border mismatch still occurs with the published 6.1.12 packages. After converting the attached template to the current schema format without changing its geometry, the original 45-degree/25 mm border case looked closely aligned. Changing only the rectangle border width to 10 mm made the generated PDF rectangle visibly shift relative to the reference lines, while the UI rectangle stayed aligned.

The UI comparison used the actual schema.ui renderers in a minimal browser harness, not the full Designer. This provides a useful current reproduction for the border/rotation geometry; the issue should remain open.
