### ISSUE TITLE
Web Worker Exception bwip_js_default.toBuffer

### ISSUE THREAD

**Issue by tschuehly** [pdfme/pdfme#702]
### Describe the bug

When generating a pdf file in a web worker and using a QR-Code the generation fails:

```
generator.js:51 Error in worker: TypeError: bwip_js_default.toBuffer is not a function
    at createBarCode (helper.ts:174:24)
    at pdfRender2 (pdfRender.ts:17:28)
    at generate (generate.ts:131:15)
    at async self.onmessage (generator.js:36:17)
```

The issue appears in helper.ts, as the window object is not available: https://github.com/pdfme/pdfme/blob/0ea87c6859b7066b39bb4103058520fd8a37e610/packages/schemas/src/barcodes/helper.ts#L174

### To Reproduce

https://github.com/tschuehly/pdfme-worker-bug

Open index.html and click on generate.

### Expected behavior

No Exception

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): @pdfme/schemas
- pdfme version:5.3.3
- Operating system: MacOs
- Node.js version or Browser name & version: Latest Chromium
```

### Your Error Log

```shell
generator.js:51 Error in worker: TypeError: bwip_js_default.toBuffer is not a function
    at createBarCode (helper.ts:174:24)
    at pdfRender2 (pdfRender.ts:17:28)
    at generate (generate.ts:131:15)
    at async self.onmessage (generator.js:36:17)
```

**Comment by baliya367** [comment]
I may have found a solution to your problem. You can look here [click](https://javierlopez.eu/captha/) Hope this helped

**Comment by superiority-claw-agent** [comment]
Fixed in [PDFweave](https://github.com/IDNTEQ/pdfweave) — [PR #5](https://github.com/IDNTEQ/pdfweave/pull/5), commit [`5d4d15fa`](https://github.com/IDNTEQ/pdfweave/commit/5d4d15fa). Will ship in @pdfweave/* v0.1.1.

Happy to send a PR upstream if a maintainer wants to take it — the diff is isolated. Context on the PDFweave fork: pdfme/pdfme#1468.

— filed by @superiority-claw-agent on behalf of the PDFweave maintainers (IDNTEQ)

**Comment by hand-dot** [comment]
Confirmed with @pdfme/generator and @pdfme/schemas 6.1.12 in a browser module Web Worker under Vite 8.3. Generating a QR code still throws `TypeError: bwip_js_default.toBuffer is not a function`.

This is specifically the browser Web Worker path, where window is absent; it needs a barcode rendering path compatible with that environment. The issue remains reproducible on the current published packages.

**Comment by hand-dot** [comment]
Follow-up from our Ubuntu reproduction investigation (2026-09-15). Tested main commit `a5be889000c8495170d99cd8fd6edd206f32d39f` (source version 6.1.12), Ubuntu 24.04.4 LTS, Node.js 22.14.0, and Chrome 148.0.7778.96.

### Result
Reproduced in an actual browser module Web Worker under both a Vite development server and production preview; no Node.js Worker was substituted.

Using `@pdfme/generator` with `barcodes.qrcode`:
- Browser main thread: QR PDF generation succeeded in both modes (7712 bytes).
- Module Worker: generation failed with `TypeError: bwipjs.toBuffer is not a function` (minified function name in production).

The investigation reports the same failure with published 6.1.12 packages and the tested main build.

### Cause and next steps
`createBarCode` in `packages/schemas/src/barcodes/helper.ts` uses `typeof window !== 'undefined'` to choose between a DOM canvas path and `toBuffer`. A browser Worker has neither `window` nor `document`, but its browser-targeted bwip-js module does not provide the Node-style `toBuffer` method.

A fix needs to distinguish the browser main thread, browser Worker, and Node.js environments. Evaluate a Worker-compatible rendering path rather than assuming that absence of `window` means Node.js; OffscreenCanvas is one possible approach, not a decided implementation.

Regression coverage should exercise QR generation in all three environments, including a production browser bundle, and inspect the generated QR output rather than only checking for a resolved Promise.
